### ISSUE TITLE
I dont think it works anymore.

### ISSUE THREAD

**Issue by Theo1996** [fp555/exh-tags-preview#5]
I have a giant cogwheel icon on the page and no tags anywhere.

**Comment by fp555** [comment]
Hello, can you explain your issue in detail? Userscript version, browser?
Make sure your userscript manager can download the https://github.com/fp555/exh-tags-preview/releases/download/v1.9.5/content.json, it contains the stylesheet that makes everything work correctly

**Comment by Theo1996** [comment]
FF 115.15 esr (same on my 91.9.1 main browser)
just dl'd  the newest script version installed with TM
and I get pic attached. I dont how to make sure if content.json is dl'd, in the externals tab it says there is an entry for content.json but I dont know if it DLs it. mousing over doesnt do shit.
![Untitled](https://github.com/user-attachments/assets/fc00d666-8085-4236-acda-c1d002f45471)

Console:
`
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data myscript.js:10:20
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery-3.2.1.js:5062:11
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. adshow.php
Request to access cookie or storage on “https://adserver.juicyads.com/adshow.php?adzone=19869” was blocked because it came from a tracker and content blocking is enabled.
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. adshow.php
Request to access cookie or storage on “https://adserver.juicyads.com/adshow.php?adzone=19553” was blocked because it came from a tracker and content blocking is enabled.
Use of Mutation Events is deprecated. Use MutationObserver instead. 2 jquery-3.2.1.js:5062:11
Some cookies are misusing the recommended “SameSite“ attribute 2
Partitioned cookie or storage access was provided to “https://chaturbate.com/tours/3/?c=5&campaign=HPR7R&p=0&tour=x1Rd&disable_sound=0” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Content-Security-Policy: The page’s settings blocked the loading of a resource at blob:https://chaturbate.com/b1e44ea7-9f45-4e0b-8f97-a90872d7aaaf (“img-src”). 3:253:20
POST
https://report-uri.mmcdn.com/r/t/csp/enforce
[HTTP/2 400 Bad Request 385ms]

Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/779-react-da6d17fa0b2e8c08f911.js
Source Map URL: 779-react-da6d17fa0b2e8c08f911.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/70-react-664a1670d69e2d3e4a6f.js
Source Map URL: 70-react-664a1670d69e2d3e4a6f.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/101-react-d1998d8bf0f2359254be.js
Source Map URL: 101-react-d1998d8bf0f2359254be.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/228-react-7a694d01c33589aebc07.js
Source Map URL: 228-react-7a694d01c33589aebc07.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/857-react-67085d6587057074bf90.js
Source Map URL: 857-react-67085d6587057074bf90.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/lib-react-bf93408bf1ea77e58ed5.js
Source Map URL: lib-react-bf93408bf1ea77e58ed5.js.map
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery-3.2.1.js:5062:11
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/200-prod-3362b55ec546aba40152.js
Source Map URL: 200-prod-3362b55ec546aba40152.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/runtime-prod-708242f2cd5e1666a9fa.js
Source Map URL: runtime-prod-708242f2cd5e1666a9fa.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/916-prod-d0e0bf1573eef96113e1.js
Source Map URL: 916-prod-d0e0bf1573eef96113e1.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/cam_iframe-prod-04daf809488c91a22131.js
Source Map URL: cam_iframe-prod-04daf809488c91a22131.js.map
Source map error: Error: request failed with status 404
Resource URL: https://web.static.mmcdn.com/cachebust/930-react-bee57050f20f5becbc10.js
Source Map URL: 930-react-bee57050f20f5becbc10.js.map
Some cookies are misusing the recommended “SameSite“ attribute 3

`

**Comment by fp555** [comment]
Those console messages have nothing to do with my script.

Looks like the stylesheet is not applying, and I'm pretty sure the issue is I'm using the [CSS nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting), but this syntax is only [supported in FF version 117+](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector#browser_compatibility).

If you can, I suggest updating your FF to the latest ESR v128.4.0 (or switch to the non-ESR channel) to fix your issue.

**Comment by Theo1996** [comment]
Well i cant switch since I am on win 7, but thank you anyway, maybe you know some other script that is older and works?

**Comment by fp555** [comment]
I suppose v1.9.0 should still mostly work for you, even if it has known bugs. Probably even v1.8.6 still works, if you want to try.

Otherwise, I'm going to stick to item 1 of the Troubleshooting section in the README.
